using Neuron.Nexus.Pages;
using Neuron.Nexus.Services;
using Neuron.Nexus.ViewModels;

namespace Neuron.Nexus;

public partial class MainPage : ContentPage
{
    public MainPage()
    {
        // Call to InitializeComponent method generated by XAML compiler to create and connect
        // all the defined UI components and event handlers. This should always be the first line in the constructor.
        InitializeComponent();

        var viewModel = Application.Current.Handler.MauiContext.Services.GetService<MainPageViewModel>();
        // This assigns the ViewModel instance to the BindingContext of the MainPage,
        // and is necessary for the data bindings defined in the XAML to work correctly.
        BindingContext = viewModel;
    }

}

