name: Build .Net MAUI Android app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'Neuron.Nexus/appsettings.json'
      env:
        ApplicationSettings.DeveloperEmail: ${{ secrets.DEVELOPER_MAIL }}
        ApplicationSettings.AppCenterSecret: ${{ secrets.APP_CENTER_SECRET }}
        ApplicationSettings.AzureKeys.AzureSubscriptionKey: ${{ secrets.AZURE_SUBSCRIPTION_KEY }}       
        ApplicationSettings.AzureKeys.AzureRegion: ${{ secrets.AZURE_REGION }}
    
    - name: Setup Keystore File 
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" > Neuron.Nexus/coded-by-kay.keystore.asc
        echo "GPG Version:"
        gpg --version
        echo "Decrypting..."
        gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD_GPG }}" --batch Neuron.Nexus/coded-by-kay.keystore.asc > Neuron.Nexus/coded-by-kay.keystore
        echo "Listing files in Neuron.Nexus directory:"
        ls -l Neuron.Nexus
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '11'
        
    - name: Install .Net MAUI
      run: |
        dotnet workload install android
        dotnet workload install maui
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build Neuron.Nexus/Neuron.Nexus.csproj -c Release -f net7.0-android /p:AndroidSigningKeyStore=${{secrets.KEYSTORE}} /p:AndroidSigningKeyAlias=${{ secrets.KEYSTORE_ALIAS }} /p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASSWORD }} /p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }} --no-restore

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: android-ci-build
        path: |
          ./**/*.aab
          ./**/*.apk        
    
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: android-ci-build

  appcenter:
      needs: build
      runs-on: ubuntu-latest
      name: AppCenter Publish
      
      steps:
      
      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: kaywib/NeuronNexus
          token: ${{secrets.APP_CENTER_SECRET}}
          group: Testers
          file: /home/runner/work/*Signed.aab
          notifyTesters: true
          debug: false

      
      
      
      
      
      
      
      
      
      
      
      
      
